name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/github-contribution-grid-snake.svg

      - name: Upload Snake
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/github-contribution-grid-snake.svg
